### ISSUE TITLE
Model transformation and detachment from within event subscriber

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-js#30]
Is there a concept of detached models, if not deep clone of model properties ?

Use Case: Do not trigger recursive events
1. I have a event subscription for update on something.
2. I receive prop as argument to that event.
3. I need to transform few properties in this prop object to something else e.g. prop.foo = newfoo
4. Step 3 triggers the change event again. Is there a better way to do this transform on the object ?

**Comment by ramukima** [comment]
The only alternative I have right now is the following which is "intense" operation -

```
obj = JSON.parse(JSON.stringify(prop.content))
// modify elements in obj instead of prop
```

**Comment by saintkepha** [comment]
Hmmm let's see.  I think the cleanest way would be to directly call prop.set with a new option `suppress: true` which will silence the event trigger for that change.  But that's assuming that you wanted to make a change back to `Model` itself.  If all you wanted to do was to have a local copy to transform it for subsequent transaction, such as writing to DB or such and did NOT want to change the internal Model data tree, then I could provide a simple .clone function that would give you a copy of the object detached from the property schema bindings.  I'm thinking what you want may be the latter since you want to freely add additional properties to the object that are NOT part of the schema?

**Comment by ramukima** [comment]
I think both features might be useful in future... 'suppress" events if needed as well 'toObject' kind of method on properties. 

I do not intend to 'extend' the model while processing events. In any case, if I try to introduce a new attribute on the existing model instance without explicitly extending the schema, the change should not be acceptable by the default setter method bound to it (can you confirm if thats the case ?).

Less priority for me as I do have the workaround as indicated above.

**Comment by saintkepha** [comment]
BTW, I'm thinking that what we want to do is to prevent the same event listener callback function from executing due to a change it introduces as part of its own callback execution?  If it makes a change that a different callback routine may be interested in, the event should still trigger for that part of the data update?

I'm considering this issue seriously because anytime recursive behavior can be triggered from seemingly normal operation (such as setting a value to a property) it should be detected and prevented. 

And it seems *unfair* to expect developers to know explicitly to suppress or make a heavy copy. 

Your workaround will not preserve the property bindings since it will make a new object simply with the values.  I can easily introduce the "clone" method for the property in question but I think there's likely a better way to handle this. 

For one, since the events are all listening on the Model instance, if we detached the head/root during the execution of the callback function, it would be "safe" since any changes you make will not propagate to be caught by the Model instance.  But what you really want is ONLY your particular callback function to not be executed - where other callback functions should operate as expected.  Which means explicit suppression inside callback function may not be desired.  I'm getting some inkling on how we may be able to make this do the Right Thing...

**Comment by saintkepha** [comment]
Ok, so here's an idea - what if we simply saved the callback function right before we called it and if we see that same callback function about to be executed, we simply ignore it?  Once the callback function finishes executing, we can clear that state and it will be back to observing state?

Hmm I think it should be more than just the callback function itself since we would also care whether the prop that triggered is the same as the callback function already running.  So it may not be 100% fool-proof but at least it will provide detection and issue a warning for possible recursive callback behavior.

**Comment by saintkepha** [comment]
So here's the latest updates to address this issue:

- event recursion detection/protection. the event callbacks now check the `stacktrace` to ensure the same callback is not found in the execution stack more than twice. it basically means that the same callback cannot be called *more than twice* as part of event propagation.
- new `suppress: true` option support as part of `Property.set` which basically will allow you to perform `prop.set <some value>, suppress: true` to prevent event propagation for that specific operation.
- improved `Property.valueOf` which can be called to provide a completely detached/unbound data object.  Basically a more *performant* version of `JSON.parse(JSON.stringify(prop.content))`.

I think these improvements should address this issue, but please note that directly changing `prop.content` will still fire the events (although infinite loop will be prevented).

Please feel free to close this issue if happy with the changes.

**Comment by ramukima** [comment]
Look good
