### ISSUE TITLE
Parser should detect syntactic errors

### ISSUE THREAD

**Issue by pnuzhdin** [corenova/yang-js#4]
I know that you are using https://www.npmjs.com/package/yang-parser which doesn't provide syntactic or semantic checks but it's too hard to use a tool like yang-js without that feature.

**Comment by saintkepha** [comment]
Hi Pavel, yes agreed, I'm currently preparing an update with 0.14.0 release to collapse the parse/preprocess/compile operation to be a singular routine so that the necessary checks take place every time.  I initially thought it may be useful to expose the underlying parse function from yang-parser more or less as-is but I don't think it serves much utility that way.

**Comment by pnuzhdin** [comment]
@saintkepha good to know. Btw, nice project!

**Comment by saintkepha** [comment]
Thanks for the great feedback.  I think I'm just a few days away from the major 0.14 release.  I'll let you know once it's released - it would be very good to get additional feedback from you.

**Comment by saintkepha** [comment]
0.14.0 published, please give it a try
